package org.example.myaggrement.entity;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/NettyMessageProto.proto

public final class NettyMessageProto {
  private NettyMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NettyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NettyMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Header header = 1;</code>
     * @return Whether the header field is set.
     */
    boolean hasHeader();
    /**
     * <code>.Header header = 1;</code>
     * @return The header.
     */
    NettyMessageProto.Header getHeader();
    /**
     * <code>.Header header = 1;</code>
     */
    NettyMessageProto.HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>.Object object = 2;</code>
     * @return Whether the object field is set.
     */
    boolean hasObject();
    /**
     * <code>.Object object = 2;</code>
     * @return The object.
     */
    NettyMessageProto.Object getObject();
    /**
     * <code>.Object object = 2;</code>
     */
    NettyMessageProto.ObjectOrBuilder getObjectOrBuilder();
  }
  /**
   * Protobuf type {@code NettyMessage}
   */
  public static final class NettyMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NettyMessage)
      NettyMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NettyMessage.newBuilder() to construct.
    private NettyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NettyMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NettyMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NettyMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              NettyMessageProto.Header.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(NettyMessageProto.Header.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              NettyMessageProto.Object.Builder subBuilder = null;
              if (object_ != null) {
                subBuilder = object_.toBuilder();
              }
              object_ = input.readMessage(NettyMessageProto.Object.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(object_);
                object_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NettyMessageProto.internal_static_NettyMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NettyMessageProto.internal_static_NettyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NettyMessageProto.NettyMessage.class, NettyMessageProto.NettyMessage.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private NettyMessageProto.Header header_;
    /**
     * <code>.Header header = 1;</code>
     * @return Whether the header field is set.
     */
    @java.lang.Override
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.Header header = 1;</code>
     * @return The header.
     */
    @java.lang.Override
    public NettyMessageProto.Header getHeader() {
      return header_ == null ? NettyMessageProto.Header.getDefaultInstance() : header_;
    }
    /**
     * <code>.Header header = 1;</code>
     */
    @java.lang.Override
    public NettyMessageProto.HeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int OBJECT_FIELD_NUMBER = 2;
    private NettyMessageProto.Object object_;
    /**
     * <code>.Object object = 2;</code>
     * @return Whether the object field is set.
     */
    @java.lang.Override
    public boolean hasObject() {
      return object_ != null;
    }
    /**
     * <code>.Object object = 2;</code>
     * @return The object.
     */
    @java.lang.Override
    public NettyMessageProto.Object getObject() {
      return object_ == null ? NettyMessageProto.Object.getDefaultInstance() : object_;
    }
    /**
     * <code>.Object object = 2;</code>
     */
    @java.lang.Override
    public NettyMessageProto.ObjectOrBuilder getObjectOrBuilder() {
      return getObject();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (object_ != null) {
        output.writeMessage(2, getObject());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (object_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getObject());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof NettyMessageProto.NettyMessage)) {
        return super.equals(obj);
      }
      NettyMessageProto.NettyMessage other = (NettyMessageProto.NettyMessage) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (hasObject() != other.hasObject()) return false;
      if (hasObject()) {
        if (!getObject()
            .equals(other.getObject())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (hasObject()) {
        hash = (37 * hash) + OBJECT_FIELD_NUMBER;
        hash = (53 * hash) + getObject().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static NettyMessageProto.NettyMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NettyMessageProto.NettyMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NettyMessageProto.NettyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NettyMessageProto.NettyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NettyMessageProto.NettyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NettyMessageProto.NettyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NettyMessageProto.NettyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NettyMessageProto.NettyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static NettyMessageProto.NettyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static NettyMessageProto.NettyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static NettyMessageProto.NettyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NettyMessageProto.NettyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NettyMessageProto.NettyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NettyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NettyMessage)
        NettyMessageProto.NettyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NettyMessageProto.internal_static_NettyMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NettyMessageProto.internal_static_NettyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NettyMessageProto.NettyMessage.class, NettyMessageProto.NettyMessage.Builder.class);
      }

      // Construct using NettyMessageProto.NettyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        if (objectBuilder_ == null) {
          object_ = null;
        } else {
          object_ = null;
          objectBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NettyMessageProto.internal_static_NettyMessage_descriptor;
      }

      @java.lang.Override
      public NettyMessageProto.NettyMessage getDefaultInstanceForType() {
        return NettyMessageProto.NettyMessage.getDefaultInstance();
      }

      @java.lang.Override
      public NettyMessageProto.NettyMessage build() {
        NettyMessageProto.NettyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public NettyMessageProto.NettyMessage buildPartial() {
        NettyMessageProto.NettyMessage result = new NettyMessageProto.NettyMessage(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (objectBuilder_ == null) {
          result.object_ = object_;
        } else {
          result.object_ = objectBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NettyMessageProto.NettyMessage) {
          return mergeFrom((NettyMessageProto.NettyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NettyMessageProto.NettyMessage other) {
        if (other == NettyMessageProto.NettyMessage.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasObject()) {
          mergeObject(other.getObject());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NettyMessageProto.NettyMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NettyMessageProto.NettyMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private NettyMessageProto.Header header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          NettyMessageProto.Header, NettyMessageProto.Header.Builder, NettyMessageProto.HeaderOrBuilder> headerBuilder_;
      /**
       * <code>.Header header = 1;</code>
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.Header header = 1;</code>
       * @return The header.
       */
      public NettyMessageProto.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? NettyMessageProto.Header.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.Header header = 1;</code>
       */
      public Builder setHeader(NettyMessageProto.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Header header = 1;</code>
       */
      public Builder setHeader(
          NettyMessageProto.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Header header = 1;</code>
       */
      public Builder mergeHeader(NettyMessageProto.Header value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              NettyMessageProto.Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Header header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Header header = 1;</code>
       */
      public NettyMessageProto.Header.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.Header header = 1;</code>
       */
      public NettyMessageProto.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              NettyMessageProto.Header.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.Header header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          NettyMessageProto.Header, NettyMessageProto.Header.Builder, NettyMessageProto.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              NettyMessageProto.Header, NettyMessageProto.Header.Builder, NettyMessageProto.HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private NettyMessageProto.Object object_;
      private com.google.protobuf.SingleFieldBuilderV3<
          NettyMessageProto.Object, NettyMessageProto.Object.Builder, NettyMessageProto.ObjectOrBuilder> objectBuilder_;
      /**
       * <code>.Object object = 2;</code>
       * @return Whether the object field is set.
       */
      public boolean hasObject() {
        return objectBuilder_ != null || object_ != null;
      }
      /**
       * <code>.Object object = 2;</code>
       * @return The object.
       */
      public NettyMessageProto.Object getObject() {
        if (objectBuilder_ == null) {
          return object_ == null ? NettyMessageProto.Object.getDefaultInstance() : object_;
        } else {
          return objectBuilder_.getMessage();
        }
      }
      /**
       * <code>.Object object = 2;</code>
       */
      public Builder setObject(NettyMessageProto.Object value) {
        if (objectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          object_ = value;
          onChanged();
        } else {
          objectBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Object object = 2;</code>
       */
      public Builder setObject(
          NettyMessageProto.Object.Builder builderForValue) {
        if (objectBuilder_ == null) {
          object_ = builderForValue.build();
          onChanged();
        } else {
          objectBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Object object = 2;</code>
       */
      public Builder mergeObject(NettyMessageProto.Object value) {
        if (objectBuilder_ == null) {
          if (object_ != null) {
            object_ =
              NettyMessageProto.Object.newBuilder(object_).mergeFrom(value).buildPartial();
          } else {
            object_ = value;
          }
          onChanged();
        } else {
          objectBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Object object = 2;</code>
       */
      public Builder clearObject() {
        if (objectBuilder_ == null) {
          object_ = null;
          onChanged();
        } else {
          object_ = null;
          objectBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Object object = 2;</code>
       */
      public NettyMessageProto.Object.Builder getObjectBuilder() {
        
        onChanged();
        return getObjectFieldBuilder().getBuilder();
      }
      /**
       * <code>.Object object = 2;</code>
       */
      public NettyMessageProto.ObjectOrBuilder getObjectOrBuilder() {
        if (objectBuilder_ != null) {
          return objectBuilder_.getMessageOrBuilder();
        } else {
          return object_ == null ?
              NettyMessageProto.Object.getDefaultInstance() : object_;
        }
      }
      /**
       * <code>.Object object = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          NettyMessageProto.Object, NettyMessageProto.Object.Builder, NettyMessageProto.ObjectOrBuilder> 
          getObjectFieldBuilder() {
        if (objectBuilder_ == null) {
          objectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              NettyMessageProto.Object, NettyMessageProto.Object.Builder, NettyMessageProto.ObjectOrBuilder>(
                  getObject(),
                  getParentForChildren(),
                  isClean());
          object_ = null;
        }
        return objectBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NettyMessage)
    }

    // @@protoc_insertion_point(class_scope:NettyMessage)
    private static final NettyMessageProto.NettyMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NettyMessageProto.NettyMessage();
    }

    public static NettyMessageProto.NettyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NettyMessage>
        PARSER = new com.google.protobuf.AbstractParser<NettyMessage>() {
      @java.lang.Override
      public NettyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NettyMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NettyMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NettyMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public NettyMessageProto.NettyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Header)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 crcCode = 1;</code>
     * @return The crcCode.
     */
    int getCrcCode();

    /**
     * <code>int32 version = 2;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <code>int64 sessionID = 3;</code>
     * @return The sessionID.
     */
    long getSessionID();

    /**
     * <code>bytes type = 4;</code>
     * @return The type.
     */
    com.google.protobuf.ByteString getType();

    /**
     * <code>bytes priority = 5;</code>
     * @return The priority.
     */
    com.google.protobuf.ByteString getPriority();

    /**
     * <code>map&lt;string, .Object&gt; attachment = 6;</code>
     */
    int getAttachmentCount();
    /**
     * <code>map&lt;string, .Object&gt; attachment = 6;</code>
     */
    boolean containsAttachment(
        java.lang.String key);
    /**
     * Use {@link #getAttachmentMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, NettyMessageProto.Object>
    getAttachment();
    /**
     * <code>map&lt;string, .Object&gt; attachment = 6;</code>
     */
    java.util.Map<java.lang.String, NettyMessageProto.Object>
    getAttachmentMap();
    /**
     * <code>map&lt;string, .Object&gt; attachment = 6;</code>
     */

    NettyMessageProto.Object getAttachmentOrDefault(
        java.lang.String key,
        NettyMessageProto.Object defaultValue);
    /**
     * <code>map&lt;string, .Object&gt; attachment = 6;</code>
     */

    NettyMessageProto.Object getAttachmentOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code Header}
   */
  public static final class Header extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Header)
      HeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Header.newBuilder() to construct.
    private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Header() {
      type_ = com.google.protobuf.ByteString.EMPTY;
      priority_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Header();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Header(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              crcCode_ = input.readInt32();
              break;
            }
            case 16: {

              version_ = input.readInt32();
              break;
            }
            case 24: {

              sessionID_ = input.readInt64();
              break;
            }
            case 34: {

              type_ = input.readBytes();
              break;
            }
            case 42: {

              priority_ = input.readBytes();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                attachment_ = com.google.protobuf.MapField.newMapField(
                    AttachmentDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, NettyMessageProto.Object>
              attachment__ = input.readMessage(
                  AttachmentDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              attachment_.getMutableMap().put(
                  attachment__.getKey(), attachment__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NettyMessageProto.internal_static_Header_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetAttachment();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NettyMessageProto.internal_static_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NettyMessageProto.Header.class, NettyMessageProto.Header.Builder.class);
    }

    public static final int CRCCODE_FIELD_NUMBER = 1;
    private int crcCode_;
    /**
     * <code>int32 crcCode = 1;</code>
     * @return The crcCode.
     */
    @java.lang.Override
    public int getCrcCode() {
      return crcCode_;
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private int version_;
    /**
     * <code>int32 version = 2;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }

    public static final int SESSIONID_FIELD_NUMBER = 3;
    private long sessionID_;
    /**
     * <code>int64 sessionID = 3;</code>
     * @return The sessionID.
     */
    @java.lang.Override
    public long getSessionID() {
      return sessionID_;
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString type_;
    /**
     * <code>bytes type = 4;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getType() {
      return type_;
    }

    public static final int PRIORITY_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString priority_;
    /**
     * <code>bytes priority = 5;</code>
     * @return The priority.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPriority() {
      return priority_;
    }

    public static final int ATTACHMENT_FIELD_NUMBER = 6;
    private static final class AttachmentDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, NettyMessageProto.Object> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, NettyMessageProto.Object>newDefaultInstance(
                  NettyMessageProto.internal_static_Header_AttachmentEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  NettyMessageProto.Object.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, NettyMessageProto.Object> attachment_;
    private com.google.protobuf.MapField<java.lang.String, NettyMessageProto.Object>
    internalGetAttachment() {
      if (attachment_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AttachmentDefaultEntryHolder.defaultEntry);
      }
      return attachment_;
    }

    public int getAttachmentCount() {
      return internalGetAttachment().getMap().size();
    }
    /**
     * <code>map&lt;string, .Object&gt; attachment = 6;</code>
     */

    @java.lang.Override
    public boolean containsAttachment(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAttachment().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAttachmentMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, NettyMessageProto.Object> getAttachment() {
      return getAttachmentMap();
    }
    /**
     * <code>map&lt;string, .Object&gt; attachment = 6;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, NettyMessageProto.Object> getAttachmentMap() {
      return internalGetAttachment().getMap();
    }
    /**
     * <code>map&lt;string, .Object&gt; attachment = 6;</code>
     */
    @java.lang.Override

    public NettyMessageProto.Object getAttachmentOrDefault(
        java.lang.String key,
        NettyMessageProto.Object defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, NettyMessageProto.Object> map =
          internalGetAttachment().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .Object&gt; attachment = 6;</code>
     */
    @java.lang.Override

    public NettyMessageProto.Object getAttachmentOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, NettyMessageProto.Object> map =
          internalGetAttachment().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (crcCode_ != 0) {
        output.writeInt32(1, crcCode_);
      }
      if (version_ != 0) {
        output.writeInt32(2, version_);
      }
      if (sessionID_ != 0L) {
        output.writeInt64(3, sessionID_);
      }
      if (!type_.isEmpty()) {
        output.writeBytes(4, type_);
      }
      if (!priority_.isEmpty()) {
        output.writeBytes(5, priority_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetAttachment(),
          AttachmentDefaultEntryHolder.defaultEntry,
          6);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (crcCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, crcCode_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, version_);
      }
      if (sessionID_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, sessionID_);
      }
      if (!type_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, type_);
      }
      if (!priority_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, priority_);
      }
      for (java.util.Map.Entry<java.lang.String, NettyMessageProto.Object> entry
           : internalGetAttachment().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, NettyMessageProto.Object>
        attachment__ = AttachmentDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, attachment__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof NettyMessageProto.Header)) {
        return super.equals(obj);
      }
      NettyMessageProto.Header other = (NettyMessageProto.Header) obj;

      if (getCrcCode()
          != other.getCrcCode()) return false;
      if (getVersion()
          != other.getVersion()) return false;
      if (getSessionID()
          != other.getSessionID()) return false;
      if (!getType()
          .equals(other.getType())) return false;
      if (!getPriority()
          .equals(other.getPriority())) return false;
      if (!internalGetAttachment().equals(
          other.internalGetAttachment())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CRCCODE_FIELD_NUMBER;
      hash = (53 * hash) + getCrcCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSessionID());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
      hash = (53 * hash) + getPriority().hashCode();
      if (!internalGetAttachment().getMap().isEmpty()) {
        hash = (37 * hash) + ATTACHMENT_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAttachment().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static NettyMessageProto.Header parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NettyMessageProto.Header parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NettyMessageProto.Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NettyMessageProto.Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NettyMessageProto.Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NettyMessageProto.Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NettyMessageProto.Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NettyMessageProto.Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static NettyMessageProto.Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static NettyMessageProto.Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static NettyMessageProto.Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NettyMessageProto.Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NettyMessageProto.Header prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Header}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Header)
        NettyMessageProto.HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NettyMessageProto.internal_static_Header_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetAttachment();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMutableAttachment();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NettyMessageProto.internal_static_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NettyMessageProto.Header.class, NettyMessageProto.Header.Builder.class);
      }

      // Construct using NettyMessageProto.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        crcCode_ = 0;

        version_ = 0;

        sessionID_ = 0L;

        type_ = com.google.protobuf.ByteString.EMPTY;

        priority_ = com.google.protobuf.ByteString.EMPTY;

        internalGetMutableAttachment().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NettyMessageProto.internal_static_Header_descriptor;
      }

      @java.lang.Override
      public NettyMessageProto.Header getDefaultInstanceForType() {
        return NettyMessageProto.Header.getDefaultInstance();
      }

      @java.lang.Override
      public NettyMessageProto.Header build() {
        NettyMessageProto.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public NettyMessageProto.Header buildPartial() {
        NettyMessageProto.Header result = new NettyMessageProto.Header(this);
        int from_bitField0_ = bitField0_;
        result.crcCode_ = crcCode_;
        result.version_ = version_;
        result.sessionID_ = sessionID_;
        result.type_ = type_;
        result.priority_ = priority_;
        result.attachment_ = internalGetAttachment();
        result.attachment_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NettyMessageProto.Header) {
          return mergeFrom((NettyMessageProto.Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NettyMessageProto.Header other) {
        if (other == NettyMessageProto.Header.getDefaultInstance()) return this;
        if (other.getCrcCode() != 0) {
          setCrcCode(other.getCrcCode());
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getSessionID() != 0L) {
          setSessionID(other.getSessionID());
        }
        if (other.getType() != com.google.protobuf.ByteString.EMPTY) {
          setType(other.getType());
        }
        if (other.getPriority() != com.google.protobuf.ByteString.EMPTY) {
          setPriority(other.getPriority());
        }
        internalGetMutableAttachment().mergeFrom(
            other.internalGetAttachment());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NettyMessageProto.Header parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NettyMessageProto.Header) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int crcCode_ ;
      /**
       * <code>int32 crcCode = 1;</code>
       * @return The crcCode.
       */
      @java.lang.Override
      public int getCrcCode() {
        return crcCode_;
      }
      /**
       * <code>int32 crcCode = 1;</code>
       * @param value The crcCode to set.
       * @return This builder for chaining.
       */
      public Builder setCrcCode(int value) {
        
        crcCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 crcCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCrcCode() {
        
        crcCode_ = 0;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>int32 version = 2;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return version_;
      }
      /**
       * <code>int32 version = 2;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 version = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private long sessionID_ ;
      /**
       * <code>int64 sessionID = 3;</code>
       * @return The sessionID.
       */
      @java.lang.Override
      public long getSessionID() {
        return sessionID_;
      }
      /**
       * <code>int64 sessionID = 3;</code>
       * @param value The sessionID to set.
       * @return This builder for chaining.
       */
      public Builder setSessionID(long value) {
        
        sessionID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 sessionID = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSessionID() {
        
        sessionID_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString type_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes type = 4;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getType() {
        return type_;
      }
      /**
       * <code>bytes type = 4;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes type = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString priority_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes priority = 5;</code>
       * @return The priority.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPriority() {
        return priority_;
      }
      /**
       * <code>bytes priority = 5;</code>
       * @param value The priority to set.
       * @return This builder for chaining.
       */
      public Builder setPriority(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        priority_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes priority = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPriority() {
        
        priority_ = getDefaultInstance().getPriority();
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, NettyMessageProto.Object> attachment_;
      private com.google.protobuf.MapField<java.lang.String, NettyMessageProto.Object>
      internalGetAttachment() {
        if (attachment_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AttachmentDefaultEntryHolder.defaultEntry);
        }
        return attachment_;
      }
      private com.google.protobuf.MapField<java.lang.String, NettyMessageProto.Object>
      internalGetMutableAttachment() {
        onChanged();;
        if (attachment_ == null) {
          attachment_ = com.google.protobuf.MapField.newMapField(
              AttachmentDefaultEntryHolder.defaultEntry);
        }
        if (!attachment_.isMutable()) {
          attachment_ = attachment_.copy();
        }
        return attachment_;
      }

      public int getAttachmentCount() {
        return internalGetAttachment().getMap().size();
      }
      /**
       * <code>map&lt;string, .Object&gt; attachment = 6;</code>
       */

      @java.lang.Override
      public boolean containsAttachment(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetAttachment().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAttachmentMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, NettyMessageProto.Object> getAttachment() {
        return getAttachmentMap();
      }
      /**
       * <code>map&lt;string, .Object&gt; attachment = 6;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, NettyMessageProto.Object> getAttachmentMap() {
        return internalGetAttachment().getMap();
      }
      /**
       * <code>map&lt;string, .Object&gt; attachment = 6;</code>
       */
      @java.lang.Override

      public NettyMessageProto.Object getAttachmentOrDefault(
          java.lang.String key,
          NettyMessageProto.Object defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, NettyMessageProto.Object> map =
            internalGetAttachment().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .Object&gt; attachment = 6;</code>
       */
      @java.lang.Override

      public NettyMessageProto.Object getAttachmentOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, NettyMessageProto.Object> map =
            internalGetAttachment().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearAttachment() {
        internalGetMutableAttachment().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .Object&gt; attachment = 6;</code>
       */

      public Builder removeAttachment(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAttachment().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, NettyMessageProto.Object>
      getMutableAttachment() {
        return internalGetMutableAttachment().getMutableMap();
      }
      /**
       * <code>map&lt;string, .Object&gt; attachment = 6;</code>
       */
      public Builder putAttachment(
          java.lang.String key,
          NettyMessageProto.Object value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAttachment().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .Object&gt; attachment = 6;</code>
       */

      public Builder putAllAttachment(
          java.util.Map<java.lang.String, NettyMessageProto.Object> values) {
        internalGetMutableAttachment().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Header)
    }

    // @@protoc_insertion_point(class_scope:Header)
    private static final NettyMessageProto.Header DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NettyMessageProto.Header();
    }

    public static NettyMessageProto.Header getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Header>
        PARSER = new com.google.protobuf.AbstractParser<Header>() {
      @java.lang.Override
      public Header parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Header(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Header> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Header> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public NettyMessageProto.Header getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ObjectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Object)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Any content = 1;</code>
     * @return Whether the content field is set.
     */
    boolean hasContent();
    /**
     * <code>.google.protobuf.Any content = 1;</code>
     * @return The content.
     */
    com.google.protobuf.Any getContent();
    /**
     * <code>.google.protobuf.Any content = 1;</code>
     */
    com.google.protobuf.AnyOrBuilder getContentOrBuilder();
  }
  /**
   * Protobuf type {@code Object}
   */
  public static final class Object extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Object)
      ObjectOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Object.newBuilder() to construct.
    private Object(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Object() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Object();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Object(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (content_ != null) {
                subBuilder = content_.toBuilder();
              }
              content_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(content_);
                content_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NettyMessageProto.internal_static_Object_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NettyMessageProto.internal_static_Object_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NettyMessageProto.Object.class, NettyMessageProto.Object.Builder.class);
    }

    public static final int CONTENT_FIELD_NUMBER = 1;
    private com.google.protobuf.Any content_;
    /**
     * <code>.google.protobuf.Any content = 1;</code>
     * @return Whether the content field is set.
     */
    @java.lang.Override
    public boolean hasContent() {
      return content_ != null;
    }
    /**
     * <code>.google.protobuf.Any content = 1;</code>
     * @return The content.
     */
    @java.lang.Override
    public com.google.protobuf.Any getContent() {
      return content_ == null ? com.google.protobuf.Any.getDefaultInstance() : content_;
    }
    /**
     * <code>.google.protobuf.Any content = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getContentOrBuilder() {
      return getContent();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (content_ != null) {
        output.writeMessage(1, getContent());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (content_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getContent());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof NettyMessageProto.Object)) {
        return super.equals(obj);
      }
      NettyMessageProto.Object other = (NettyMessageProto.Object) obj;

      if (hasContent() != other.hasContent()) return false;
      if (hasContent()) {
        if (!getContent()
            .equals(other.getContent())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static NettyMessageProto.Object parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NettyMessageProto.Object parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NettyMessageProto.Object parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NettyMessageProto.Object parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NettyMessageProto.Object parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NettyMessageProto.Object parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NettyMessageProto.Object parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NettyMessageProto.Object parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static NettyMessageProto.Object parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static NettyMessageProto.Object parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static NettyMessageProto.Object parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NettyMessageProto.Object parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NettyMessageProto.Object prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Object}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Object)
        NettyMessageProto.ObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NettyMessageProto.internal_static_Object_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NettyMessageProto.internal_static_Object_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NettyMessageProto.Object.class, NettyMessageProto.Object.Builder.class);
      }

      // Construct using NettyMessageProto.Object.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (contentBuilder_ == null) {
          content_ = null;
        } else {
          content_ = null;
          contentBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NettyMessageProto.internal_static_Object_descriptor;
      }

      @java.lang.Override
      public NettyMessageProto.Object getDefaultInstanceForType() {
        return NettyMessageProto.Object.getDefaultInstance();
      }

      @java.lang.Override
      public NettyMessageProto.Object build() {
        NettyMessageProto.Object result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public NettyMessageProto.Object buildPartial() {
        NettyMessageProto.Object result = new NettyMessageProto.Object(this);
        if (contentBuilder_ == null) {
          result.content_ = content_;
        } else {
          result.content_ = contentBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NettyMessageProto.Object) {
          return mergeFrom((NettyMessageProto.Object)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NettyMessageProto.Object other) {
        if (other == NettyMessageProto.Object.getDefaultInstance()) return this;
        if (other.hasContent()) {
          mergeContent(other.getContent());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NettyMessageProto.Object parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NettyMessageProto.Object) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.Any content_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> contentBuilder_;
      /**
       * <code>.google.protobuf.Any content = 1;</code>
       * @return Whether the content field is set.
       */
      public boolean hasContent() {
        return contentBuilder_ != null || content_ != null;
      }
      /**
       * <code>.google.protobuf.Any content = 1;</code>
       * @return The content.
       */
      public com.google.protobuf.Any getContent() {
        if (contentBuilder_ == null) {
          return content_ == null ? com.google.protobuf.Any.getDefaultInstance() : content_;
        } else {
          return contentBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any content = 1;</code>
       */
      public Builder setContent(com.google.protobuf.Any value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          content_ = value;
          onChanged();
        } else {
          contentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any content = 1;</code>
       */
      public Builder setContent(
          com.google.protobuf.Any.Builder builderForValue) {
        if (contentBuilder_ == null) {
          content_ = builderForValue.build();
          onChanged();
        } else {
          contentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any content = 1;</code>
       */
      public Builder mergeContent(com.google.protobuf.Any value) {
        if (contentBuilder_ == null) {
          if (content_ != null) {
            content_ =
              com.google.protobuf.Any.newBuilder(content_).mergeFrom(value).buildPartial();
          } else {
            content_ = value;
          }
          onChanged();
        } else {
          contentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any content = 1;</code>
       */
      public Builder clearContent() {
        if (contentBuilder_ == null) {
          content_ = null;
          onChanged();
        } else {
          content_ = null;
          contentBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any content = 1;</code>
       */
      public com.google.protobuf.Any.Builder getContentBuilder() {
        
        onChanged();
        return getContentFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any content = 1;</code>
       */
      public com.google.protobuf.AnyOrBuilder getContentOrBuilder() {
        if (contentBuilder_ != null) {
          return contentBuilder_.getMessageOrBuilder();
        } else {
          return content_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : content_;
        }
      }
      /**
       * <code>.google.protobuf.Any content = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getContentFieldBuilder() {
        if (contentBuilder_ == null) {
          contentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getContent(),
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        return contentBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Object)
    }

    // @@protoc_insertion_point(class_scope:Object)
    private static final NettyMessageProto.Object DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NettyMessageProto.Object();
    }

    public static NettyMessageProto.Object getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Object>
        PARSER = new com.google.protobuf.AbstractParser<Object>() {
      @java.lang.Override
      public Object parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Object(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Object> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Object> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public NettyMessageProto.Object getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NettyMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NettyMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Header_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Header_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Header_AttachmentEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Header_AttachmentEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Object_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Object_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035proto/NettyMessageProto.proto\032\031google/" +
      "protobuf/any.proto\"@\n\014NettyMessage\022\027\n\006he" +
      "ader\030\001 \001(\0132\007.Header\022\027\n\006object\030\002 \001(\0132\007.Ob" +
      "ject\"\306\001\n\006Header\022\017\n\007crcCode\030\001 \001(\005\022\017\n\007vers" +
      "ion\030\002 \001(\005\022\021\n\tsessionID\030\003 \001(\003\022\014\n\004type\030\004 \001" +
      "(\014\022\020\n\010priority\030\005 \001(\014\022+\n\nattachment\030\006 \003(\013" +
      "2\027.Header.AttachmentEntry\032:\n\017AttachmentE" +
      "ntry\022\013\n\003key\030\001 \001(\t\022\026\n\005value\030\002 \001(\0132\007.Objec" +
      "t:\0028\001\"/\n\006Object\022%\n\007content\030\001 \001(\0132\024.googl" +
      "e.protobuf.AnyB\023B\021NettyMessageProtob\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_NettyMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NettyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NettyMessage_descriptor,
        new java.lang.String[] { "Header", "Object", });
    internal_static_Header_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Header_descriptor,
        new java.lang.String[] { "CrcCode", "Version", "SessionID", "Type", "Priority", "Attachment", });
    internal_static_Header_AttachmentEntry_descriptor =
      internal_static_Header_descriptor.getNestedTypes().get(0);
    internal_static_Header_AttachmentEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Header_AttachmentEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Object_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Object_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Object_descriptor,
        new java.lang.String[] { "Content", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
